version: '3'

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

  backend:
    build: ./server
    container_name: wallet_server_container
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: wallet_client_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  logs:
  data: